const express = require('express');
const cors = require('cors');
const multer = require('multer');
const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

const app = express();
const port = process.env.PORT || 3000;

app.use(cors());
app.use(express.static('public'));

// Configure multer storage
const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        const uploadDir = 'uploads/';
        if (!fs.existsSync(uploadDir)) {
            fs.mkdirSync(uploadDir, { recursive: true });
        }
        cb(null, uploadDir);
    },
    filename: (req, file, cb) => {
        cb(null, file.fieldname + '_' + Date.now() + '.csv');
    }
});
const upload = multer({ storage });

app.post('/api/generate-timetable', upload.fields([{ name: 'courses', maxCount: 1 }, { name: 'students', maxCount: 1 }]), (req, res) => {
    if (!req.files || !req.files.courses || !req.files.students) {
        return res.status(400).json({ error: 'Both courses and students CSV files are required.' });
    }

    const coursesPath = req.files.courses[0].path;
    const studentsPath = req.files.students[0].path;
    const timetableCsvOutput = `public/timetable_output.csv`;
    const imageOutput = `public/timetable_graph.png`;
    
    // Ensure public folder exists for outputs
    if (!fs.existsSync('public')) {
        fs.mkdirSync('public', { recursive: true });
    }

    // Spawn Python Subprocess. Use env var, Windows local .venv, or default to python3
    const isWindows = process.platform === "win32";
    const pythonExecutable = process.env.PYTHON_PATH || (isWindows ? path.resolve('.venv/Scripts/python.exe') : 'python3');
    const mainScript = path.resolve('main.py');
    
    console.log(`Executing python algorithm on uploaded datasets using ${pythonExecutable}...`);
    const pythonProcess = spawn(pythonExecutable, [
        mainScript,
        '--courses', coursesPath,
        '--students', studentsPath,
        '--output', timetableCsvOutput,
        '--image_output', imageOutput
    ]);

    let pyStdout = '';
    let pyStderr = '';

    pythonProcess.stdout.on('data', (data) => pyStdout += data.toString());
    pythonProcess.stderr.on('data', (data) => pyStderr += data.toString());

    pythonProcess.on('close', (code) => {
        // Cleanup uploads
        fs.unlinkSync(coursesPath);
        fs.unlinkSync(studentsPath);

        if (code !== 0) {
            console.error('Python execution error:', pyStderr);
            return res.status(500).json({ error: 'Algorithm processing failed.', details: pyStderr });
        }

        console.log('Python processing finished successfully.');
        
        // Read the CSV output to send back to client
        if (fs.existsSync(timetableCsvOutput)) {
            const csvData = fs.readFileSync(timetableCsvOutput, 'utf-8');
            // Basic CSV parsing to JSON array for quick table rendering
            const rows = csvData.trim().split('\n');
            const headers = rows.shift().split(',');
            const parsedData = rows.map(row => {
                const values = row.split(',');
                let obj = {};
                headers.forEach((header, i) => {
                    obj[header.trim()] = values[i] ? values[i].trim() : '';
                });
                return obj;
            });

            return res.json({
                message: "Timetable Optimized Successfully",
                timetable: parsedData,
                imageUrl: `/timetable_graph.png?t=${Date.now()}` // Cache buster
            });
        } else {
            return res.status(500).json({ error: 'Timetable CSV was not generated by algorithm.' });
        }
    });
});

app.listen(port, () => {
    console.log(`Server is running at http://localhost:${port}`);
});
